# Generated by Django 3.1 on 2020-08-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='Book Number'),
        ),
    ]
