# Generated by Django 3.1 on 2020-08-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuevotesbook',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
            preserve_default=False,
        ),
    ]
